# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1LogingehezuheutigenTagundReservierung():
  def setup_method(self):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_1LogingehezuheutigenTagundReservierung(self):
    self.driver.get("https://raumbuchung.bibliothek.kit.edu/sitzplatzreservierung/day.php?year=2021&month=07&day=11&area=20&room=140")
    self.driver.set_window_size(958, 1048)
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(2) input:nth-child(3)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(2) input:nth-child(3)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "NewUserName").send_keys("KITCardNumber")
    self.driver.find_element(By.ID, "NewUserPassword").send_keys("KITBibPassword")
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    self.driver.find_element(By.ID, "EULA_INPUT").click()
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    self.driver.find_element(By.LINK_TEXT, "gehe zum heutigen Tag").click()
    self.driver.find_element(By.CSS_SELECTOR, ".new:nth-child(14) a").click()
    self.driver.find_element(By.NAME, "save_button").click()

if __name__ == "__main__":
    test = Test1LogingehezuheutigenTagundReservierung()
    test.setup_method()
    test.test_1LogingehezuheutigenTagundReservierung()
    test.teardown_method()
